# Copyright 2024 Marc-Antoine Ruel. All rights reserved.
# Use of this source code is governed under the Apache License, Version 2.0
# that can be found in the LICENSE file.

on: [push, pull_request]
name: Run tests
jobs:
  test:
    name: "test on ${{matrix.os}}"
    runs-on: "${{matrix.os}}"
    strategy:
      matrix:
        os: [ubuntu-latest, macos-14]
        # macos-latest (currently macos-13) doesn't contain Xcode 15.
        # windows-latest gets a compilation error because net/if.h is missing.
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v4
      with:
        path: ellee
    - name: checkout esphome
      uses: actions/checkout@v4
      with:
        repository: esphome/esphome
        path: esphome
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: ./setup.sh
      if: runner.os != 'Windows'
      run: ./ellee/setup.sh
    - name: pip3 install
      if: runner.os == 'Windows'
      run: pip3 install -r ellee/requirements.txt
    - name: ./test.py
      run: |
        if [ "$RUNNER_OS" != "Windows" ]; then
          source ./ellee/venv/bin/activate
        fi
        ./ellee/test.py
