# Copyright 2024 Marc-Antoine Ruel. All rights reserved.
# Use of this source code is governed under the Apache License, Version 2.0
# that can be found in the LICENSE file.

on: [push, pull_request]
name: Run tests
jobs:
  test:
    name: "test on ${{matrix.os}}"
    runs-on: "${{matrix.os}}"
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v4
      with:
        path: ellee
    - name: checkout esphome
      uses: actions/checkout@v4
      with:
        repository: esphome/esphome
        path: esphome
    - name: ./test.py
      run: ./ellee/test.py
